INSERT INTO USERS (USER_ID, EMAIL, PASSWORD, NICKNAME) VALUES (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin');
INSERT INTO USERS (USER_ID, EMAIL, PASSWORD, NICKNAME) VALUES (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user');

INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('NORMAL');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ADMIN');
INSERT INTO AUTHORITY (AUTHORITY_NAME) values ('ROOT');

INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'NORMAL');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (1, 'ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_NAME) values (2, 'ADMIN');